export {default as Home} from './home/Home';
export {default as Admin} from './admin/Admin';
export {default as Contact} from './contact/Contact';
export {default as Cart} from './cart/Cart';
export {default as Orders} from './orders/Orders';
export {default as Login} from './autentication/login/Login';
export {default as Register} from './autentication/register/Register';
export {default as ResetPassword} from './autentication/resetPassword/ResetPassword';
export {default as CheckoutSuccess} from './checkoutSuccess/CheckoutSuccess';
export {default as Dashboard} from './admin/dashboard/Dashboard';
export {default as Products} from './admin/products/Products';
export {default as AdminOrders} from './admin/adminOrders/AdminOrders'
export {default as Users} from './admin/users/Users';
export {default as CreateProduct} from './admin/products/CreateProduct';